import argparse
import json
import sqlite3
from dataclasses import dataclass, field
from typing import Any

from .utils import sizeof_fmt, sql_execute, timestamp_to_str
from .variables import DEFAULT_RUN, ActivityRef, VariableRef

# pylint: disable=too-many-lines


@dataclass
class ArchiveInfo:
    """Archive metadata stored in the info table."""

    id: str
    name: str
    version: str
    mod_time: int


@dataclass
class ArchiveEntry:
    """Archive entry tied to a directory."""

    id: int
    tar_name: str
    system: str


@dataclass
class DirectoryInfo:
    """Directory metadata with archive entries."""

    id: int
    name: str
    mod_time: int
    del_time: int
    archives: list[ArchiveEntry] = field(default_factory=list)
    has_archive: bool = False


@dataclass
class HostInfo:
    """Host metadata with its directories."""

    id: int
    hostname: str
    long_hostname: str
    directories: list[DirectoryInfo] = field(default_factory=list)


@dataclass
class KeyInfo:
    """Encryption key metadata."""

    id: int
    key: str


@dataclass
class FileInfo:
    """Replica file metadata."""

    name: str
    len_orig: int
    len_compressed: int
    mod_time: int
    checksum: str


@dataclass
class ResolutionInfo:
    """Image resolution metadata."""

    x: int
    y: int


@dataclass
class ReplicaFlags:
    """Replica state flags."""

    deleted: bool
    encrypted: bool
    accuracy: bool
    archive: bool
    embedded: bool


@dataclass
class ReplicaInfo:  # pylint: disable=too-many-instance-attributes
    """Replica metadata entry."""

    host_id: int
    dir_id: int
    archive_id: int
    name: str
    mod_time: int
    del_time: int
    key_id: int
    size: int
    flags: ReplicaFlags
    files: list[FileInfo] = field(default_factory=list)
    resolution: ResolutionInfo | None = None


@dataclass
class DatasetInfo:
    """Dataset metadata entry."""

    uuid: str
    name: str
    mod_time: int
    del_time: int
    file_format: str
    replicas: dict[int, ReplicaInfo] = field(default_factory=dict)
    metadata: dict | None = None


@dataclass
class TimeSeriesInfo:
    """Time series metadata with datasets."""

    name: str
    datasets: dict[int, DatasetInfo] = field(default_factory=dict)


@dataclass(frozen=True)
class RunInfo:
    """One campaign run with a stable identity."""

    id: int
    uuid: str
    name: str


@dataclass(frozen=True)
class StepMappingInfo:
    """Compact mapping from output chunk indices to one activity input."""

    output_variable_id: int
    output_start: int
    count: int
    encoding: str
    source_start: int | None
    stride: int | None
    explicit_steps: tuple[int, ...] = ()

    def source_step(self, output_index: int) -> int:
        """Return the source step for one output index without expanding the mapping."""
        offset = output_index - self.output_start
        if offset < 0 or offset >= self.count:
            raise IndexError(f"Output index {output_index} is outside this mapping")
        if self.encoding == "explicit":
            return self.explicit_steps[offset]
        if self.source_start is None or self.stride is None:
            raise ValueError(f"Invalid {self.encoding} source-step mapping")
        return int(self.source_start) + offset * int(self.stride)


@dataclass
class ActivityInputInfo:
    """One role-qualified entity used by an activity."""

    id: int
    role: str
    variable_id: int
    reference: VariableRef
    step_mappings: list[StepMappingInfo] = field(default_factory=list)


@dataclass(frozen=True)
class ActivityOutputInfo:
    """One role-qualified entity generated by an activity."""

    id: int
    role: str
    variable_id: int
    reference: VariableRef


@dataclass
class ActivityInfo:  # pylint: disable=too-many-instance-attributes
    """A controlled action and its immediate provenance connections."""

    id: int
    uuid: str
    run_id: int | None
    run: str | None
    category: str
    action: str
    action_spec: Any = None
    inputs: list[ActivityInputInfo] = field(default_factory=list)
    outputs: list[ActivityOutputInfo] = field(default_factory=list)

    @property
    def reference(self) -> ActivityRef:
        return ActivityRef(self.uuid)


@dataclass
class VariableChunkInfo:
    """One ordered payload belonging to a logical variable."""

    id: int
    chunk_index: int
    payload_dataset_id: int
    payload_dataset_name: str
    payload_dataset_uuid: str
    payload_file_format: str


@dataclass
class LogicalVariableInfo:  # pylint: disable=too-many-instance-attributes
    """A data-product entity registered in the campaign."""

    id: int
    uuid: str
    run_id: int
    run: str
    definition_id: int
    definition: str
    dataset_id: int
    dataset: str
    variable: str
    primary: bool = False
    preferred_preview: VariableRef | None = None
    generated_by: ActivityRef | None = None
    used_by: list[ActivityRef] = field(default_factory=list)
    chunks: list[VariableChunkInfo] = field(default_factory=list)

    @property
    def reference(self) -> VariableRef:
        return VariableRef(self.run, self.dataset, self.variable)


@dataclass
class InfoResult:  # pylint: disable=too-many-instance-attributes
    """Aggregated archive information."""

    archive: ArchiveInfo
    hosts: list[HostInfo] = field(default_factory=list)
    keys: list[KeyInfo] = field(default_factory=list)
    time_series: dict[int, TimeSeriesInfo] = field(default_factory=dict)
    runs: dict[int, RunInfo] = field(default_factory=dict)
    variables: dict[int, LogicalVariableInfo] = field(default_factory=dict)
    activities: dict[int, ActivityInfo] = field(default_factory=dict)
    datasets: dict[int, DatasetInfo] = field(default_factory=dict)
    _variable_index: dict[VariableRef, int] = field(default_factory=dict, repr=False)
    _activity_index: dict[str, int] = field(default_factory=dict, repr=False)

    def find_variable(
        self,
        dataset: str,
        variable: str,
        run: str = DEFAULT_RUN,
    ) -> LogicalVariableInfo:
        """Find a logical variable by its public identity."""
        reference = VariableRef(run, dataset, variable)
        variable_id = self._variable_index.get(reference)
        if variable_id is not None:
            return self.variables[variable_id]
        for item in self.variables.values():
            if item.reference == reference:
                self._variable_index[reference] = item.id
                return item
        raise LookupError(f"Logical variable not found: {run}/{dataset}/{variable}")

    def find_activity(self, activity: ActivityRef | str) -> ActivityInfo:
        """Find an activity by its stable UUID."""
        activity_uuid = activity.uuid if isinstance(activity, ActivityRef) else str(activity)
        activity_id = self._activity_index.get(activity_uuid)
        if activity_id is not None:
            return self.activities[activity_id]
        for item in self.activities.values():
            if item.uuid == activity_uuid:
                self._activity_index[activity_uuid] = item.id
                return item
        raise LookupError(f"Activity not found: {activity_uuid}")

    def _variable_for_ref(self, reference: VariableRef) -> LogicalVariableInfo:
        return self.find_variable(reference.dataset, reference.variable, reference.run)

    def primary_variables(
        self,
        *,
        run: str | None = None,
        definition: str | None = None,
    ) -> list[LogicalVariableInfo]:
        """Return explicit primary bindings, optionally filtered by run or definition."""
        return [
            item
            for item in self.variables.values()
            if item.primary
            and (run is None or item.run == run)
            and (definition is None or item.definition == definition)
        ]

    def root_sources(self, reference: VariableRef) -> list[LogicalVariableInfo]:
        """Return all reachable variables that have no known derivation source."""
        roots: dict[int, LogicalVariableInfo] = {}
        visited: set[int] = set()

        def visit(item: LogicalVariableInfo) -> None:
            if item.id in visited:
                return
            visited.add(item.id)
            if item.generated_by is None:
                roots[item.id] = item
                return
            activity = self.find_activity(item.generated_by)
            for source in activity.inputs:
                visit(self.variables[source.variable_id])

        visit(self._variable_for_ref(reference))
        return [roots[key] for key in sorted(roots)]

    def derived_variables_from(
        self,
        reference: VariableRef,
        *,
        action: str | None = None,
        transitive: bool = True,
    ) -> list[LogicalVariableInfo]:
        """Return direct or transitive variables derived from a source."""
        start = self._variable_for_ref(reference)
        result: dict[int, LogicalVariableInfo] = {}
        pending = list(start.used_by)
        visited_activities: set[int] = set()
        while pending:
            activity_ref = pending.pop(0)
            activity_info = self.find_activity(activity_ref)
            if activity_info.id in visited_activities:
                continue
            visited_activities.add(activity_info.id)
            for output in activity_info.outputs:
                derived = self.variables[output.variable_id]
                if action is None or activity_info.action == action:
                    result[derived.id] = derived
                if transitive:
                    pending.extend(derived.used_by)
        return [result[key] for key in sorted(result)]

    def paths_to_root_sources(self, reference: VariableRef) -> list[list[VariableRef]]:
        """Return every direct-provenance path from a variable to a root source."""
        paths: list[list[VariableRef]] = []

        def visit(item: LogicalVariableInfo, path: list[VariableRef]) -> None:
            next_path = [*path, item.reference]
            if item.generated_by is None:
                paths.append(next_path)
                return
            activity = self.find_activity(item.generated_by)
            for source in activity.inputs:
                visit(self.variables[source.variable_id], next_path)

        visit(self._variable_for_ref(reference), [])
        return paths


# ruff: disable[W291]
# fmt: off
SELECT_DATA_CMD = """
SELECT
    d.rowid             AS ds_id,
    d.name              AS ds_name,
    d.uuid              AS ds_uuid,
    d.modtime           AS ds_modtime,
    d.deltime           AS ds_deltime,
    d.fileformat        AS ds_fileformat,
    d.tsid              AS ds_tsid,

    r.rowid             AS rep_id,
    r.hostid            AS hostid,
    r.dirid             AS dirid,
    r.archiveid         AS archiveid,
    r.name              AS rep_name,
    r.modtime           AS rep_modtime,
    r.deltime           AS rep_deltime,
    r.keyid             AS keyid,
    r.size              AS rep_size,

    rf.fileid           AS repfile_id,

    f.name              AS file_name,
    f.compression       AS compression,
    f.lenorig           AS lenorig,
    f.lencompressed     AS lencompressed,
    f.modtime           AS file_modtime,
    f.checksum          AS checksum,

    acc.rowid           AS acc_id

FROM dataset AS d
JOIN replica AS r
    ON r.datasetid = d.rowid
LEFT JOIN repfiles AS rf
    ON rf.replicaid = r.rowid
LEFT JOIN file AS f
    ON f.fileid = rf.fileid
LEFT JOIN accuracy AS acc
    ON acc.replicaid = r.rowid
WHERE d.fileformat = 'ADIOS' OR d.fileformat = 'HDF5'
ORDER BY d.rowid, r.rowid, f.fileid;
"""

SELECT_IMAGES_CMD = """
SELECT
    d.rowid             AS ds_id, 
    d.name              AS ds_name,
    d.uuid              AS ds_uuid,
    d.modtime           AS ds_modtime, 
    d.deltime           AS ds_deltime,
    d.fileformat        AS ds_fileformat,
    d.tsid              AS ds_tsid,

    r.rowid             AS rep_id,
    r.hostid            AS hostid,
    r.dirid             AS dirid,
    r.archiveid         AS archiveid,
    r.name              AS rep_name,
    r.modtime           AS rep_modtime,
    r.deltime           AS rep_deltime,
    r.keyid             AS keyid,
    r.size              AS rep_size,

    rf.fileid           AS repfile_id,

    f.name              AS file_name,
    f.compression       AS compression,
    f.lenorig           AS lenorig,
    f.lencompressed     AS lencompressed,
    f.modtime           AS file_modtime,
    f.checksum          AS checksum,

    res.x               AS res_x,
    res.y               AS res_y

FROM dataset AS d
JOIN replica AS r
    ON r.datasetid = d.rowid
LEFT JOIN repfiles AS rf
    ON rf.replicaid = r.rowid
LEFT JOIN file AS f
    ON f.fileid = rf.fileid
LEFT JOIN resolution AS res
    ON res.replicaid = r.rowid
WHERE d.fileformat = 'IMAGE'
ORDER BY d.rowid, r.rowid, f.fileid;
"""

SELECT_TEXTS_CMD = """
SELECT
    d.rowid             AS ds_id, 
    d.name              AS ds_name,
    d.uuid              AS ds_uuid,
    d.modtime           AS ds_modtime, 
    d.deltime           AS ds_deltime,
    d.fileformat        AS ds_fileformat,
    d.tsid              AS ds_tsid,

    r.rowid             AS rep_id,
    r.hostid            AS hostid,
    r.dirid             AS dirid,
    r.archiveid         AS archiveid,
    r.name              AS rep_name,
    r.modtime           AS rep_modtime,
    r.deltime           AS rep_deltime,
    r.keyid             AS keyid,
    r.size              AS rep_size,

    rf.fileid           AS repfile_id,

    f.name              AS file_name,
    f.compression       AS compression,
    f.lenorig           AS lenorig,
    f.lencompressed     AS lencompressed,
    f.modtime           AS file_modtime,
    f.checksum          AS checksum

FROM dataset AS d
JOIN replica AS r
    ON r.datasetid = d.rowid
LEFT JOIN repfiles AS rf
    ON rf.replicaid = r.rowid
LEFT JOIN file AS f
    ON f.fileid = rf.fileid
WHERE d.fileformat = 'TEXT'
ORDER BY d.rowid, r.rowid, f.fileid;
"""

# ruff: enable[W291]
# fmt: on


# pylint: disable=too-many-locals
# pylint: disable=too-many-positional-arguments
# pylint: disable=too-many-arguments
def info_row(
    args: argparse.Namespace,
    info_data: InfoResult,
    row,
    accuracy: bool,
    embedded: bool,
    resolution: ResolutionInfo | None,
    dirs_archived: dict[int, bool],
) -> DatasetInfo | None:

    dataset_del_time = int(row["ds_deltime"])
    replica_del_time = int(row["rep_deltime"])
    if (dataset_del_time + replica_del_time) > 0 and not args.show_deleted:
        return None

    dataset_id = int(row["ds_id"])
    ts_id = int(row["ds_tsid"])
    if ts_id > 0:
        dataset_info = info_data.time_series[ts_id].datasets.setdefault(
            dataset_id,
            DatasetInfo(
                row["ds_uuid"],
                row["ds_name"],
                int(row["ds_modtime"]),
                dataset_del_time,
                row["ds_fileformat"],
            ),
        )
    else:
        dataset_info = info_data.datasets.setdefault(
            dataset_id,
            DatasetInfo(
                row["ds_uuid"],
                row["ds_name"],
                int(row["ds_modtime"]),
                dataset_del_time,
                row["ds_fileformat"],
            ),
        )

    replica_id = int(row["rep_id"])
    replica_info = dataset_info.replicas.get(replica_id)
    if replica_info is None:
        dir_id = int(row["dirid"])
        key_id = int(row["keyid"])

        flags = ReplicaFlags(
            deleted=replica_del_time > 0,
            encrypted=key_id > 0,
            accuracy=accuracy,
            archive=dirs_archived.get(dir_id, False),
            embedded=embedded,
        )

        replica_info = ReplicaInfo(
            host_id=int(row["hostid"]),
            dir_id=dir_id,
            archive_id=int(row["archiveid"]),
            name=row["rep_name"],
            mod_time=int(row["rep_modtime"]),
            del_time=replica_del_time,
            key_id=key_id,
            size=int(row["rep_size"]),
            flags=flags,
        )
        dataset_info.replicas[replica_id] = replica_info

    if resolution is not None:
        replica_info.resolution = resolution

    if args.list_files and row["repfile_id"] is not None:
        cks = row["checksum"] if args.show_checksum else ""
        replica_info.files.append(
            FileInfo(
                name=row["file_name"],
                len_orig=int(row["lenorig"]),
                len_compressed=int(row["lencompressed"]),
                mod_time=int(row["file_modtime"]),
                checksum=cks,
            )
        )
    return dataset_info


def info_datas(  # pylint: disable=too-many-locals
    args: argparse.Namespace,
    info_data: InfoResult,
    cur: sqlite3.Cursor,
    dirs_archived: dict[int, bool],
):
    #
    # ADIOS and HDF5 datasets
    #
    res = sql_execute(cur, SELECT_DATA_CMD)
    for row in res:
        info_row(
            args,
            info_data,
            row,
            accuracy=(row["acc_id"] is not None),
            embedded=False,
            resolution=None,
            dirs_archived=dirs_archived,
        )


def info_images(  # pylint: disable=too-many-locals
    args: argparse.Namespace,
    info_data: InfoResult,
    cur: sqlite3.Cursor,
    dirs_archived: dict[int, bool],
):
    #
    # IMAGE datasets
    #
    res = sql_execute(cur, SELECT_IMAGES_CMD)
    for row in res:
        res_x = int(row["res_x"])
        res_y = int(row["res_y"])
        dataset_info = info_row(
            args,
            info_data,
            row,
            accuracy=False,
            embedded=(row["repfile_id"] is not None),
            resolution=ResolutionInfo(res_x, res_y),
            dirs_archived=dirs_archived,
        )
        if dataset_info is None:
            continue


def info_texts(  # pylint: disable=too-many-locals
    args: argparse.Namespace,
    info_data: InfoResult,
    cur: sqlite3.Cursor,
    dirs_archived: dict[int, bool],
):
    #
    # TEXT datasets
    #
    res = sql_execute(cur, SELECT_TEXTS_CMD)
    for row in res:
        info_row(
            args,
            info_data,
            row,
            accuracy=False,
            embedded=(row["repfile_id"] is not None),
            resolution=None,
            dirs_archived=dirs_archived,
        )


def _info_json_value(value: str | None) -> Any:
    if value is None:
        return None
    try:
        return json.loads(value)
    except (json.JSONDecodeError, TypeError):
        return None


def info_variables(  # pylint: disable=too-many-locals,too-many-statements
    info_data: InfoResult,
    cur: sqlite3.Cursor,
) -> None:
    """Load data-product entities and the activity graph into an InfoResult."""
    required_tables = {
        "campaign_run",
        "variable_definition",
        "logical_variable",
        "primary_variable",
        "activity_category",
        "activity_kind",
        "action_spec",
        "activity",
        "activity_input",
        "activity_output",
        "variable_chunk",
        "activity_input_step_mapping",
    }
    placeholders = ", ".join("?" for _name in required_tables)
    rows = sql_execute(
        cur,
        f"select name from sqlite_master where type = 'table' and name in ({placeholders})",
        tuple(required_tables),
    ).fetchall()
    if {str(row[0]) for row in rows} != required_tables:
        return

    for row in sql_execute(cur, "select runid, uuid, name from campaign_run order by runid"):
        run = RunInfo(id=int(row["runid"]), uuid=str(row["uuid"]), name=str(row["name"]))
        info_data.runs[run.id] = run

    variable_rows = sql_execute(
        cur,
        "select lv.variableid, lv.uuid, lv.runid, run.name as run_name, "
        "lv.definitionid, definition.name as definition_name, "
        "lv.datasetid, d.name as dataset_name, lv.name, "
        "primary_value.variableid is not null as is_primary, "
        "preview.name as preview_name, preview_run.name as preview_run_name, "
        "preview_dataset.name as preview_dataset_name "
        "from logical_variable as lv "
        "join campaign_run as run on run.runid = lv.runid "
        "join variable_definition as definition on definition.definitionid = lv.definitionid "
        "join dataset as d on d.rowid = lv.datasetid and d.deltime = 0 "
        "left join primary_variable as primary_value on primary_value.variableid = lv.variableid "
        "left join logical_variable as preview on preview.variableid = lv.preferred_preview_id "
        "left join campaign_run as preview_run on preview_run.runid = preview.runid "
        "left join dataset as preview_dataset on preview_dataset.rowid = preview.datasetid "
        "order by lv.variableid",
    )
    for row in variable_rows:
        preview = None
        if row["preview_name"] is not None:
            preview = VariableRef(
                str(row["preview_run_name"]),
                str(row["preview_dataset_name"]),
                str(row["preview_name"]),
            )
        variable_id = int(row["variableid"])
        loaded_variable = LogicalVariableInfo(
            id=variable_id,
            uuid=str(row["uuid"]),
            run_id=int(row["runid"]),
            run=str(row["run_name"]),
            definition_id=int(row["definitionid"]),
            definition=str(row["definition_name"]),
            dataset_id=int(row["datasetid"]),
            dataset=str(row["dataset_name"]),
            variable=str(row["name"]),
            primary=bool(row["is_primary"]),
            preferred_preview=preview,
        )
        info_data.variables[variable_id] = loaded_variable
        info_data._variable_index[loaded_variable.reference] = variable_id  # pylint: disable=protected-access

    activity_rows = sql_execute(
        cur,
        "select activity.activityid, activity.uuid, activity.runid, run.name as run_name, "
        "category.name as category, kind.name as action, spec.metadata as action_spec "
        "from activity join activity_kind as kind on kind.kindid = activity.kindid "
        "join activity_category as category on category.categoryid = kind.categoryid "
        "left join campaign_run as run on run.runid = activity.runid "
        "left join action_spec as spec on spec.specid = activity.specid "
        "order by activity.activityid",
    )
    for row in activity_rows:
        activity_id = int(row["activityid"])
        loaded_activity = ActivityInfo(
            id=activity_id,
            uuid=str(row["uuid"]),
            run_id=int(row["runid"]) if row["runid"] is not None else None,
            run=str(row["run_name"]) if row["run_name"] is not None else None,
            category=str(row["category"]),
            action=str(row["action"]),
            action_spec=_info_json_value(row["action_spec"]),
        )
        info_data.activities[activity_id] = loaded_activity
        info_data._activity_index[loaded_activity.uuid] = activity_id  # pylint: disable=protected-access

    inputs_by_id: dict[int, ActivityInputInfo] = {}
    input_rows = sql_execute(
        cur,
        "select input.inputid, input.activityid, input.variableid, input.role, "
        "run.name as run_name, dataset.name as dataset_name, variable.name as variable_name "
        "from activity_input as input "
        "join logical_variable as variable on variable.variableid = input.variableid "
        "join campaign_run as run on run.runid = variable.runid "
        "join dataset on dataset.rowid = variable.datasetid "
        "order by input.activityid, input.inputid",
    )
    for row in input_rows:
        input_activity = info_data.activities.get(int(row["activityid"]))
        input_variable = info_data.variables.get(int(row["variableid"]))
        if input_activity is None or input_variable is None:
            continue
        activity_input = ActivityInputInfo(
            id=int(row["inputid"]),
            role=str(row["role"]),
            variable_id=input_variable.id,
            reference=VariableRef(
                str(row["run_name"]),
                str(row["dataset_name"]),
                str(row["variable_name"]),
            ),
        )
        input_activity.inputs.append(activity_input)
        inputs_by_id[activity_input.id] = activity_input
        if input_activity.reference not in input_variable.used_by:
            input_variable.used_by.append(input_activity.reference)

    output_rows = sql_execute(
        cur,
        "select output.outputid, output.activityid, output.variableid, output.role, "
        "run.name as run_name, dataset.name as dataset_name, variable.name as variable_name "
        "from activity_output as output "
        "join logical_variable as variable on variable.variableid = output.variableid "
        "join campaign_run as run on run.runid = variable.runid "
        "join dataset on dataset.rowid = variable.datasetid "
        "order by output.activityid, output.outputid",
    )
    for row in output_rows:
        output_activity = info_data.activities.get(int(row["activityid"]))
        output_variable = info_data.variables.get(int(row["variableid"]))
        if output_activity is None or output_variable is None:
            continue
        activity_output = ActivityOutputInfo(
            id=int(row["outputid"]),
            role=str(row["role"]),
            variable_id=output_variable.id,
            reference=VariableRef(
                str(row["run_name"]),
                str(row["dataset_name"]),
                str(row["variable_name"]),
            ),
        )
        output_activity.outputs.append(activity_output)
        output_variable.generated_by = output_activity.reference

    chunk_rows = sql_execute(
        cur,
        "select chunk.chunkid, chunk.variableid, chunk.chunk_index, chunk.payload_datasetid, "
        "payload.name as payload_name, payload.uuid as payload_uuid, payload.fileformat as payload_fileformat "
        "from variable_chunk as chunk "
        "join dataset as payload on payload.rowid = chunk.payload_datasetid and payload.deltime = 0 "
        "order by chunk.variableid, chunk.chunk_index",
    )
    for row in chunk_rows:
        chunk_variable = info_data.variables.get(int(row["variableid"]))
        if chunk_variable is None:
            continue
        chunk = VariableChunkInfo(
            id=int(row["chunkid"]),
            chunk_index=int(row["chunk_index"]),
            payload_dataset_id=int(row["payload_datasetid"]),
            payload_dataset_name=str(row["payload_name"]),
            payload_dataset_uuid=str(row["payload_uuid"]),
            payload_file_format=str(row["payload_fileformat"]),
        )
        chunk_variable.chunks.append(chunk)

    mapping_rows = sql_execute(
        cur,
        "select inputid, output_variableid, output_start, count, encoding, "
        "source_start, stride, explicit_steps from activity_input_step_mapping "
        "order by inputid, output_variableid, output_start",
    )
    for row in mapping_rows:
        mapped_input = inputs_by_id.get(int(row["inputid"]))
        if mapped_input is None:
            continue
        raw_explicit = _info_json_value(row["explicit_steps"])
        explicit = tuple(int(step) for step in raw_explicit) if isinstance(raw_explicit, list) else ()
        mapped_input.step_mappings.append(
            StepMappingInfo(
                output_variable_id=int(row["output_variableid"]),
                output_start=int(row["output_start"]),
                count=int(row["count"]),
                encoding=str(row["encoding"]),
                source_start=(int(row["source_start"]) if row["source_start"] is not None else None),
                stride=int(row["stride"]) if row["stride"] is not None else None,
                explicit_steps=explicit,
            )
        )


def collect_info(  # pylint: disable=too-many-locals,too-many-statements
    args: argparse.Namespace, con: sqlite3.Connection
) -> InfoResult:
    cur = con.cursor()
    res = sql_execute(cur, "select id, name, version, modtime from info")
    row = res.fetchone()
    info_datasets = InfoResult(
        archive=ArchiveInfo(
            id=row[0],
            name=row[1],
            version=row[2],
            mod_time=row[3],
        )
    )

    #
    # Hosts and directories
    #
    delete_condition_where = " where deltime = 0"
    delete_condition_and = " and deltime = 0"
    if args.show_deleted:
        delete_condition_where = ""
        delete_condition_and = ""
    res = sql_execute(
        cur,
        "select rowid, hostname, longhostname from host" + delete_condition_where + " order by rowid",
    )
    hosts = res.fetchall()
    dirs_archived: dict[int, bool] = {}
    for host in hosts:
        host_info = HostInfo(
            id=host[0],
            hostname=host[1],
            long_hostname=host[2],
        )
        res2 = sql_execute(
            cur,
            "select rowid, name, modtime, deltime from directory "
            + 'where hostid = "'
            + str(host[0])
            + '"'
            + delete_condition_and
            + " order by rowid",
        )
        dirs = res2.fetchall()
        for dirrec in dirs:
            if dirrec[3] == 0 or args.show_deleted:
                # check if it's archive dir
                res3 = sql_execute(
                    cur,
                    f"select rowid, tarname, system from archive where dirid = {dirrec[0]} order by rowid",
                )
                archs = res3.fetchall()
                archive_entries: list[ArchiveEntry] = []
                for arch in archs:
                    archive_entries.append(ArchiveEntry(id=arch[0], tar_name=arch[1], system=arch[2]))
                has_archive = bool(archive_entries)
                dirs_archived[dirrec[0]] = has_archive
                host_info.directories.append(
                    DirectoryInfo(
                        id=dirrec[0],
                        name=dirrec[1],
                        mod_time=dirrec[2],
                        del_time=dirrec[3],
                        archives=archive_entries,
                        has_archive=has_archive,
                    )
                )
        info_datasets.hosts.append(host_info)

    #
    # Keys
    #
    res = sql_execute(cur, "select rowid, keyid from key order by rowid")
    keys = res.fetchall()
    for key in keys:
        info_datasets.keys.append(KeyInfo(id=key[0], key=key[1]))

    #
    # Time Series
    #
    res_ts = sql_execute(cur, "select tsid, name from timeseries order by tsid")
    for ts in res_ts:
        ts_id = int(ts[0])
        ts_info = TimeSeriesInfo(name=ts[1])
        info_datasets.time_series[ts_id] = ts_info

    #
    # Datasets
    #
    if not args.list_replicas and not args.list_files:
        res_ds = sql_execute(
            cur,
            "select rowid, uuid, name, modtime, deltime, fileformat, tsid from dataset "
            "where fileformat != 'VARIABLES'" + delete_condition_and + " order by rowid",
        )
        for dataset in res_ds:
            dataset_id = int(dataset[0])
            dataset_info = DatasetInfo(
                uuid=dataset[1],
                name=dataset[2],
                mod_time=dataset[3],
                del_time=dataset[4],
                file_format=dataset[5],
            )
            tsid = dataset[6]
            if tsid > 0:
                info_datasets.time_series[tsid].datasets[dataset_id] = dataset_info
            else:
                info_datasets.datasets[dataset_id] = dataset_info
    else:
        info_datas(args, info_datasets, cur, dirs_archived)
        info_texts(args, info_datasets, cur, dirs_archived)
        info_images(args, info_datasets, cur, dirs_archived)

    info_variables(info_datasets, cur)
    return info_datasets


def format_info_dataset_lines(  # pylint: disable=too-many-locals
    dataset_info: DatasetInfo,
) -> list[str]:
    lines = []
    time_str = timestamp_to_str(dataset_info.mod_time)
    dataset_line = f"    {dataset_info.uuid}   {dataset_info.file_format:6}  {time_str}   {dataset_info.name}"
    if dataset_info.del_time > 0:
        dataset_line += f"  - deleted {timestamp_to_str(dataset_info.del_time)}"
    lines.append(dataset_line)

    for replica_id, replica_info in dataset_info.replicas.items():
        flags = replica_info.flags
        flag_del = "D" if flags.deleted else "-"
        flag_encrypted = "k" if flags.encrypted else "-"
        flag_accuracy = "a" if flags.accuracy else "-"
        flag_archive = "A" if flags.archive else "-"
        flag_remote = "e" if flags.embedded else "r"
        replica_line = (
            f"  {replica_id:>7} {flag_remote}{flag_encrypted}{flag_accuracy}{flag_archive}{flag_del} "
            f"{replica_info.dir_id}"
        )
        if replica_info.archive_id > 0:
            replica_line += f".{replica_info.archive_id}"
        else:
            replica_line += "  "

        if dataset_info.file_format == "IMAGE" and replica_info.resolution is not None:
            res = replica_info.resolution
            resolution_text = f" {res.x} x {res.y}".rjust(14)
        else:
            resolution_text = " ".rjust(14)
        replica_line += f"{resolution_text}"

        replica_line += f" {sizeof_fmt(replica_info.size):>11}  {timestamp_to_str(replica_info.mod_time)}"
        replica_line += f"      {replica_info.name}"
        if flags.deleted:
            replica_line += f"  - deleted {timestamp_to_str(replica_info.del_time)}"
        lines.append(replica_line)

        for file_info in replica_info.files:
            if replica_info.key_id > 0:
                prefix = " " * 30 + f"k{replica_info.key_id:<3}"
            else:
                prefix = " " * 34
            file_line = prefix + f"{sizeof_fmt(file_info.len_compressed):>11}  {timestamp_to_str(file_info.mod_time)}"
            if file_info.checksum:
                file_line += f"         {file_info.checksum}  {file_info.name}"
            else:
                file_line += f"         {file_info.name}"
            lines.append(file_line)

    return lines


def format_info(info_data: InfoResult) -> str:  # pylint: disable=too-many-statements
    lines = []
    archive_info = info_data.archive
    created_time = timestamp_to_str(archive_info.mod_time)
    lines.append(f"{archive_info.name}, version {archive_info.version}, created on {created_time}")
    lines.append("")

    lines.append("Hosts and directories:")
    for host_info in info_data.hosts:
        lines.append(f"  {host_info.hostname}   longhostname = {host_info.long_hostname}")
        for dir_info in host_info.directories:
            archive_system = "  "
            if dir_info.archives:
                archive_system = f"  - Archive: {dir_info.archives[0].system}"
            lines.append(f"     {dir_info.id}. {dir_info.name}{archive_system}")
            for archive_entry in dir_info.archives:
                tar_name = archive_entry.tar_name if archive_entry.tar_name else "."
                lines.append(f"       {dir_info.id}.{archive_entry.id} {tar_name}")
    lines.append("")

    if info_data.keys:
        lines.append("Encryption keys:")
        for key_info in info_data.keys:
            lines.append(f"  k{key_info.id}. {key_info.key}")
        lines.append("")

    if info_data.time_series:
        lines.append("Time-series and their datasets:")
        for _ts_id, ts_info in info_data.time_series.items():
            lines.append(f"  {ts_info.name}")
            for _ds_id, dataset_info in sorted(ts_info.datasets.items()):
                lines.extend(format_info_dataset_lines(dataset_info))
        lines.append("")

    if info_data.datasets:
        lines.append("Other Datasets:")
        for _ds_id, dataset_info in sorted(info_data.datasets.items()):
            lines.extend(format_info_dataset_lines(dataset_info))
        lines.append("")

    if info_data.variables:
        lines.append("Variables:")
        for _variable_id, variable in sorted(info_data.variables.items()):
            primary = " primary" if variable.primary else ""
            lines.append(
                f"  {variable.run}/{variable.dataset}/{variable.variable}   definition={variable.definition}{primary}"
            )
            if variable.generated_by is not None:
                lines.append(f"      generated by: {variable.generated_by.uuid}")
            if variable.chunks:
                lines.append(f"      chunks: {len(variable.chunks)}")
            if variable.preferred_preview is not None:
                lines.append(
                    f"      preferred preview: {variable.preferred_preview.run}/"
                    f"{variable.preferred_preview.dataset}/"
                    f"{variable.preferred_preview.variable}"
                )
        lines.append("")

    if info_data.activities:
        lines.append("Activities:")
        for _activity_id, activity in sorted(info_data.activities.items()):
            lines.append(f"  {activity.uuid}   {activity.category}/{activity.action}")
            for activity_input in activity.inputs:
                lines.append(
                    f"      input[{activity_input.role}]: {activity_input.reference.run}/"
                    f"{activity_input.reference.dataset}/{activity_input.reference.variable}"
                )
            for output in activity.outputs:
                lines.append(
                    f"      output[{output.role}]: {output.reference.run}/"
                    f"{output.reference.dataset}/{output.reference.variable}"
                )
        lines.append("")

    return "\n".join(lines)


def print_info(info_data: InfoResult):
    output_text = format_info(info_data)
    if output_text:
        print(output_text)
